# Generated by Django 4.1.1 on 2022-11-27 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'evn_topic',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('post_at', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255, unique=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.CharField(blank=True, max_length=255)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='api_news.topic')),
            ],
            options={
                'db_table': 'evn_news',
                'ordering': ['-post_at'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api_news.news')),
            ],
            options={
                'db_table': 'evn_keyword',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('src', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_news.news')),
            ],
            options={
                'db_table': 'evn_image',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('paragraph', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api_news.news')),
            ],
            options={
                'db_table': 'evn_content',
            },
        ),
    ]
